In [1]:
import numpy as np

from base_methods.base_sklearn import generate_probabilities
from ebm.dataset import get_train_dev_data, get_test_data
from params import MultiBaseParams, SingleBaseParams
from utils.feature_names import *
from utils.metrics import confidence_intervals
from utils.stacking import get_feature_name_sets_with_highest_probable_accuracy

Load train and test data (takes some time)

In [2]:
train = get_train_dev_data()
test = get_test_data()

Run grid search of parameters:

In [ ]:
from examples.run_grid_search import run_grid_search
params = SingleBaseParams(feature_name, classifier, dirname=sklearn_master_name, params={}, pca=False)
parameters = {
        'clf__C': [0.1, 1, 10, 100, 1000],
        'clf__gamma': [1, 0.1, 0.01, 0.001, 0.0001],
        'clf__kernel': ['rbf', 'linear']}
run_grid_search(train=train, test=test, params=params, parameters=parameters)

In order to calculate confidence intervals for a particular set of parameters, run:

In [3]:
accuracies = []
feature_name = publication_type_key
classifier = RandomForestClassifier_name
for i in range(15):
    params = SingleBaseParams(feature_name, classifier, dirname=sklearn_master_name, params={}, pca=False)
    a = generate_probabilities(train, test, params, test_only=True)
    accuracies.append(a * 100)

l, r = confidence_intervals(accuracies)
m = float(np.mean([l, r]))
results = "%s & %s & %.3f & %.1f-%.1f" % (feature_name, classifier, m, l, r)
print(results)

Using TensorFlow backend.


score = 0.7049
score = 0.7049
score = 0.7049
score = 0.7049
score = 0.6995
score = 0.7049
score = 0.6995
score = 0.7049
score = 0.7049
score = 0.7049
score = 0.7049
score = 0.7104
score = 0.7049
score = 0.7049
score = 0.7049
publication_type & RandomForestClassifier & 70.455 & 70.3-70.6


In order to generate intermediate features, run:

In [7]:
params = SingleBaseParams(feature_name=publication_type_key, classifier=RandomForestClassifier_name, dirname="new", params={}, pca=False)
generate_probabilities(train=train, test=test, params=params, test_only=False)
params.serialize()

0/86 (0.00%)
score = 0.7000
1/86 (1.16%)
score = 0.8000
2/86 (2.33%)
score = 0.7000
3/86 (3.49%)
score = 0.8000
4/86 (4.65%)
score = 0.8000
5/86 (5.81%)
score = 0.4000
6/86 (6.98%)
score = 0.8000
7/86 (8.14%)
score = 0.5000
8/86 (9.30%)
score = 1.0000
9/86 (10.47%)
score = 0.3000
10/86 (11.63%)
score = 0.9000
11/86 (12.79%)
score = 0.4000
12/86 (13.95%)
score = 0.8000
13/86 (15.12%)
score = 0.6000
14/86 (16.28%)
score = 0.5000
15/86 (17.44%)
score = 0.5000
16/86 (18.60%)
score = 0.9000
17/86 (19.77%)
score = 0.8000
18/86 (20.93%)
score = 1.0000
19/86 (22.09%)
score = 0.5000
20/86 (23.26%)
score = 0.6000
21/86 (24.42%)
score = 0.5000
22/86 (25.58%)
score = 0.5000
23/86 (26.74%)
score = 0.6000
24/86 (27.91%)
score = 0.6000
25/86 (29.07%)
score = 0.7000
26/86 (30.23%)
score = 0.8000
27/86 (31.40%)
score = 0.5000
28/86 (32.56%)
score = 0.4000
29/86 (33.72%)
score = 0.8000
30/86 (34.88%)
score = 0.5000
31/86 (36.05%)
score = 0.9000
32/86 (37.21%)
score = 0.5000
33/86 (38.37%)
score = 0.6000

In order to generate intermediate features from multiple features just use:

In [13]:
params = MultiBaseParams(features=[publication_type_key, title_key], classifier=AdaBoostClassifier_name, dirname="new", params={}, pca=False)

Ensemble algorithms:

In [15]:
from ensemble_methods.ensemble_auctioning import run
params1 = SingleBaseParams(feature_name=publication_type_key, classifier=RandomForestClassifier_name, dirname="new", params={}, pca=False)
params2 = SingleBaseParams(feature_name=title_key, classifier=RandomForestClassifier_name, dirname="sklearn", params={}, pca=False)

a = run([params1, params2], verbose=False, with_save=False, name="new")

/Users/aleksandra/PycharmProjects/mgr/venv/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1268: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


max_acc 0.31812865497076026 3.4000000000000012
min_aed 0.44853801169590646 3.4000000000000012
accuracy (A): 0.31812865497076026
balanced_accuracy (BA): 0.3109187487704112
balanced_accuracy_adjusted (BA): -0.03362187684438316
precision (P): 0.3021012541288641
recall (R): 0.31812865497076026
jaccard (IoU): 0.15753896541692705
f1_score (F): 0.2601768581855642
aed_score (AED): 0.44853801169590646
confusion_matrix (C):
[[184  76   0]
 [303  88   0]
 [184  20   0]]


In [18]:
from ensemble_methods.ensemble_consensus import run
params1 = SingleBaseParams(feature_name=publication_type_key, classifier=RandomForestClassifier_name, dirname="new", params={}, pca=False)
params2 = SingleBaseParams(feature_name=title_key, classifier=RandomForestClassifier_name, dirname="sklearn", params={}, pca=False)

a, line = run([params1, params2], name="new", verbose=False, with_save=False)

<params.SingleBaseParams object at 0x11fcca320> 0.6350877192982456
<params.SingleBaseParams object at 0x11fccae80> 0.5169590643274854
<params.SingleBaseParams object at 0x11fcca320> 0.7103825136612022
<params.SingleBaseParams object at 0x11fccae80> 0.5081967213114754
accuracy (A): 0.6557377049180327
balanced_accuracy (BA): 0.59190462110332
balanced_accuracy_adjusted (BA): 0.38785693165498
precision (P): 0.7124817734173736
recall (R): 0.6557377049180327
jaccard (IoU): 0.47017326949001814
f1_score (F): 0.631683239272597
aed_score (AED): 0.1721311475409836
confusion_matrix (C):
[[19 37  0]
 [ 5 81  3]
 [ 0 18 20]]


In [20]:
from ensemble_methods.ensemble_game_theory import run
params1 = SingleBaseParams(feature_name=publication_type_key, classifier=RandomForestClassifier_name, dirname="new", params={}, pca=False)
params2 = SingleBaseParams(feature_name=title_key, classifier=RandomForestClassifier_name, dirname="sklearn", params={}, pca=False)

a, line = run([params1, params2], verbose=False, with_save=False)

accuracy (A): 0.7049180327868853
balanced_accuracy (BA): 0.6677895581650756
balanced_accuracy_adjusted (BA): 0.5016843372476133
precision (P): 0.7241683007652482
recall (R): 0.7049180327868853
jaccard (IoU): 0.5396418297676399
f1_score (F): 0.6984485312732961
aed_score (AED): 0.15027322404371585
confusion_matrix (C):
[[29 26  1]
 [10 76  3]
 [ 0 14 24]]


Run ensemble classifiers

In [24]:
from ensemble_methods.ensemble_sklearn import run
params1 = SingleBaseParams(feature_name=publication_type_key, classifier=RandomForestClassifier_name, dirname="new", params={}, pca=False)
params2 = SingleBaseParams(feature_name=title_key, classifier=RandomForestClassifier_name, dirname="sklearn", params={}, pca=False)

mea = run([params1, params2], RandomForestClassifier_name, to_binary=False, use_only_ab=False, balanced=True)

best_score 0.7170998632010944
0.7170998632010944 0.03298147568364048
best_params {}


Run ensemble neural networks

In [25]:
from ensemble_methods.ensemble_keras import run
params1 = SingleBaseParams(feature_name=publication_type_key, classifier=RandomForestClassifier_name, dirname="new", params={}, pca=False)
params2 = SingleBaseParams(feature_name=title_key, classifier=RandomForestClassifier_name, dirname="sklearn", params={}, pca=False)

mea = run([params1, params2], 'adadelta', use_only_ab=False)

183/183 [==============================] - 0s 156us/step
publication type, title M(0) & adadelta & 68.25 & 66.04-70.47 \\

